### ISSUE TITLE
Unpickling Error

### ISSUE THREAD

**Issue by ma-tooth** [mnmjh1215/2019-1-diya-CartoonGAN#1]
Hi, 

Thanks for your work on this implementation! It's really exciting.

I'm having an issue getting the generator to load:

Traceback (most recent call last):
  File "main.py", line 169, in <module>
    main()
  File "main.py", line 125, in main
    load_generator(generator, args.model_path)
  File "main.py", line 76, in load_generator
    checkpoint = torch.load(checkpoint_path, map_location=Config.device)
  File "/Users/admin/opt/miniconda3/envs/2019-1-diya-CartoonGAN/lib/python3.6/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/admin/opt/miniconda3/envs/2019-1-diya-CartoonGAN/lib/python3.6/site-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '#'.

Could you please provide the specific package versions in your development environment? Perhaps we can add it as a requirements.txt to the git.

Skylar

**Comment by ma-tooth** [comment]
Figured it out. I wasn't using the correct model.
